[[redirects]]
	from="https://jb-color-tool.netlify.com/*"
	to="https://color.joelb.dev/:splat"
	status=301
	force = true
	
[[redirects]]
	from="/*"
	to="index.html"
	status=200

[build]
  	# base = ""
	publish = "build/"
	command = "yarn build"
	# functions = "functions/"

[[headers]]
	for = "static/*"
	[headers.values]
		cache-control = '''
		public,
		max-age=31536000'''